language: php
php:
  - 5.3
  - 5.4
  - 5.5
  
env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'drop database if exists parm_namespaced_tests; create database parm_namespaced_tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql parm_namespaced_tests < tests/data/namespaced-test-data.sql; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'drop database if exists parm_global_tests; create database parm_global_tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql parm_global_tests < tests/data/global-test-data.sql; fi"
  - composer install --prefer-source --dev

script: phpunit
